/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false` (hash: fcb49e224155518171c4dc82f42de520)
interface __BaseEnv_Env {
	SLATEDB_BUCKET: R2Bucket;
	SLATEDB_CONTAINERS: DurableObjectNamespace<import("./worker/index").SlateDbContainer>;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./worker/index");
		durableNamespaces: "SlateDbContainer";
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
