/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false` (hash: dbd4900f2c97d4bb85993cf4d0fd6138)
interface __BaseEnv_Env {
	R2_BUCKET: "slatedb-cloudflare-container";
	SLATEDB_CONTAINERS: DurableObjectNamespace<import("./worker/index").SlateDbContainer>;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./worker/index");
		durableNamespaces: "SlateDbContainer";
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "R2_BUCKET">> {}
}
