[package]
name = "slatedb-cloudflare"
version = "0.1.0"
edition = "2024"
publish = false
license = "Apache-2.0"

[lib]
crate-type = ["cdylib"]

[dependencies]
async-trait = "0.1.89"
bytes = "1.11.1"
chrono = "0.4.43"
futures = "0.3.32"
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0.149"
slatedb = { path = "vendor/slatedb", default-features = false }
worker = "=0.8.5"

[target.'cfg(target_arch = "wasm32")'.dependencies]
getrandom = { version = "0.3.4", features = ["wasm_js"] }
uuid = { version = "1.24.1", features = ["js"] }

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
object_store = { version = "0.14.1", default-features = false, features = ["fs", "tokio"] }

[patch.crates-io]
object_store = { path = "vendor/object-store" }
slatedb-common = { path = "vendor/slatedb-common" }
slatedb-txn-obj = { path = "vendor/slatedb-txn-obj" }

[profile.release]
lto = true
codegen-units = 1
